Web/Source/SWeb/LifeBox/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'LifeBox'
urlpatterns = [

    #MAIN
    path('', views.connexion, name ='connexion'),
    path('home', views.home, name = 'home'),
    path('logout', views.deconnexion, name='deconnexion'),
    path('parameter', views.parameter, name = 'parameter'),

    #CALENDAR
    path('calendar', views.CalendarView.as_view(), name = 'calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/new/<day>/<month>/<year>', views.event, name='event_new'),
    path('event/edit/<event_id>/', views.event, name='event_edit'),
    path('delete_event/<event_id>',views.delete_event, name='delete_event'),

    #CAPTEUR
    path('sensor', views.sensor, name = 'sensor'),
    path('delete_sensor/<num_module>', views.delete_sensor, name = 'delete_sensor'),
    path('sensor_status/<id_sensor>', views.sensor_status, name = 'sensor_status'),
    path('all_sensor_offline', views.all_sensor_offline, name = 'all_sensor_offline'),
    path('sensor_modif/<id_sensor>', views.sensor_modif, name = 'sensor_modif'),

    #GROUP
    path('create_group', views.create_group, name = 'create_group'),
    path('group/<id_group>', views.group, name = 'group'),
    path('modif_group/<id_group>', views.modif_group, name = 'modif_group'),
    path('delete_group/<id_group>', views.delete_group, name = 'delete_group'),
    path('create_group_association/<id_group>', views.create_group_association, name = 'create_group_association'),
    path('delete_group_association/<id_group>/<id_sensor>', views.delete_group_association, name = 'delete_group_association'),

    #REGUL
    path('create_regul/<id_group>', views.create_regul, name = 'create_regul'),
    path('modif_regul/<id_regul>', views.modif_regul, name = 'modif_regul'),
    path('delete_regul/<id_regul>', views.delete_regul, name = 'delete_regul'),
    path('regul/setpoint/<id_regul>/<value>', views.modif_setpoint, name = 'modif_setpoint'),
    path('regul/status/<id_regul>/<value>', views.regul_on, name = 'regul_on'),
    path('create_regul_association/<id_regul>/<type_sensor>', views.create_regul_association, name = 'create_regul_association'),
    path('delete_regul_association/<id_regul>/<id_sensor>', views.delete_regul_association, name = 'delete_regul_association'),

    #NOTIFICATION
    path('notif/delete/<id_notif>', views.delete_notif, name = 'delete_notif'),

    #DATA
    path('update_status/<num_module>/<type_tram>/<online>', views.update_status_sensor, name = 'update_status_sensor'),
    path('<num_module>/<type_value_tram>/<value>', views.insert_data, name = 'insert_data'),

    #OTHER
    path('404', views.error, name = 'error'),
    path('clean', views.clean, name = 'clean'),
    path('clean_data', views.clean_data, name = 'clean_data'),

    #REGUL TYPE DATA
    path('list_dict', views.list_dict, name = 'list_dict'),
    path('edit_dict/<id_dict>', views.modif_dict, name = 'modif_dict'),
    path('delete_dict/<id_dict>', views.delete_dict, name = 'delete_dict'),

    #WEATHER
    path('weather', views.weather, name = 'weather'),
]

Web/Source/SWeb/SWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

handler404 = 'LifeBox.views.handler404'

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('LifeBox.urls')),
    prefix_default_language=True,
)

Web/Source/SWeb/LifeBox/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

class Sensor(models.Model):
    """ Tables des capteures"""
    num_module = models.IntegerField(verbose_name = "Numero du module")
    type_value_tram = models.IntegerField(verbose_name = "Type valeur tram")
    name = models.CharField(max_length=100, verbose_name = "Nom du capteur")
    icon = models.CharField(max_length=100, null=True, blank=True, verbose_name = "icon")
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")
    online = models.BooleanField(default=False, verbose_name = "Online / offline" )

    class Meta:
        verbose_name = "sensor"
        ordering = ['num_module']

    def __str__(self):
        return self.name
        
class Group(models.Model):
    """ Tables des groupes"""
    name = models.CharField(max_length=100, verbose_name = "Nom du groupe")
    icon = models.CharField(max_length=100, null=True, blank=True, verbose_name = "icon")
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")
    sensor = models.ManyToManyField(Sensor, through='Group_ass', related_name="groups")
    
    class Meta:
        verbose_name = "group"
        ordering = ['name']

    def __str__(self):
        return self.name
        
class Notification(models.Model):
    """ Tables des notifications"""
    ntype = models.IntegerField(default=1, verbose_name = "Type de notif")
    level = models.IntegerField(verbose_name = "Niveau de notif")
    content = models.CharField(max_length=100, verbose_name = "Contenu notif")
    date = models.DateTimeField(default=timezone.now, verbose_name = "Date creation")
    def _get_delta(self):
        "Returns delta time."
        return (self.end_date - timezone.now()).days

    delta = property(_get_delta)
    end_date = models.DateTimeField(default=timezone.now, verbose_name = "Endtime")

    class Meta:
        verbose_name = "Notification"
        ordering = ['date']
     
class Regul(models.Model):
    """ Tables des regulations"""
    name = models.CharField(max_length=100, verbose_name = "Regulation name")
    icon = models.CharField(max_length=100, null=True, blank=True, verbose_name = "icon")
    type_regul = models.IntegerField(blank=True, null=True, verbose_name = "Regulation type (Temperature, ...)")
    setpoint = models.CharField(blank=True, null=True, max_length=100, verbose_name = "Regulation setpoint string")
    measure = models.CharField(blank=True, null=True, max_length=100, verbose_name = "Regulation measure")
    action = models.CharField(blank=True, null=True, max_length=100, verbose_name = "Regulation action")
    on = models.BooleanField(default=False, verbose_name = "On/Off" )
    sensor = models.ManyToManyField(Sensor, through='Regul_ass', related_name="reguls")
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")
    
    class Meta:
        verbose_name = "regul"
        ordering = ['name']

    def __str__(self):
        return self.name
        
class Group_ass(models.Model):
    """ Tables des association groupes"""
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="reguls")
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")
    
    class Meta:
        verbose_name = "Group association"
        ordering = ['date']
                
class Regul_ass(models.Model):
    """ Tables des association regulation"""
    regul = models.ForeignKey(Regul, on_delete=models.CASCADE)
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    type_sensor = models.IntegerField(verbose_name = "Le type du capteur si il est utilisé en 1 = Mesure, 2 = Action")
    # expert_mode = models.BooleanField(default=False, verbose_name = "Mode expert" )
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")

    class Meta:
        verbose_name = "Regulation association"
        ordering = ['date']
                
class Data(models.Model):
    """ Tables des données des capteurs"""
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    num_module = models.IntegerField(verbose_name = "Numero du module, un module est un microcontroleur")
    type_value_tram = models.IntegerField(verbose_name = "Type valeur tram est une des mesures fait par un module")
    value = models.CharField(blank=True, null=True, max_length=100, verbose_name = "value")
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")

    class Meta:
            verbose_name = "Data"
            ordering = ['date']

class Parameter(models.Model):
    """ Tables des paramètres"""
    name = models.CharField(max_length=100, verbose_name = "Nom du parametre")
    value = models.CharField(max_length=100, verbose_name = "Valeur du parametre")
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")
    
    class Meta:
        verbose_name = "Parameter"
        ordering = ['name']

class Event(models.Model):
    """ Tables des evenements"""
    title = models.CharField(max_length=200)
    icon = models.CharField(max_length=100, null=True, blank=True, verbose_name = "icon")
    description = models.TextField()
    start_time = models.DateTimeField(verbose_name="Date de debut de l'evenement")
    end_time = models.DateTimeField(verbose_name="Date de fin de l'evenement")

    @property
    def get_html_url(self):
        url = reverse('LifeBox:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class RegulForType(models.Model):
    """ Tables des type de regul"""
    type_value_tram = models.IntegerField(verbose_name = "Type valeur tram")
    name = models.CharField(max_length=100, verbose_name = "Nom du parametre")
    value = models.IntegerField(verbose_name = "Value for that name")
    signe = models.CharField(max_length=100, verbose_name = "signe")
    date = models.DateTimeField(default=timezone.now, verbose_name="date created")

    class Meta:
            verbose_name = "RegulForType"
            ordering = ['type_value_tram']

Web/Source/SWeb/LifeBox/forms.py
from django import forms
from .models import *
from LifeBox.utils import *
from LifeBox.regul import *
from django.utils.translation import gettext_lazy as _

class ConnexionForm(forms.Form):
    """ forms des users """
    username = forms.CharField(label=_("Username"), max_length=30)
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    
class CreateGroupForm(forms.Form):
    """ forms des groupes"""
    name = forms.CharField(max_length=100, label=_("Group name"), required=True)
    icon = forms.CharField(max_length=100, label=_("Icon"), required=True)
       
class Group_assForm(forms.Form):
    """ forms des associations des groupes/capteurs"""
    group = forms.ModelChoiceField(queryset=Group.objects.all(),label = _("Group name"), required=True, empty_label = None)
    sensor = forms.ModelChoiceField(queryset=Sensor.objects.none(), label = _("Sensors"), required=True)   
    
    def __init__(self,*args,**kwargs):
        self.value = kwargs.pop('id', None)
        super(Group_assForm,self).__init__(*args,**kwargs)
        if self.value:
            group = Group.objects.filter(id=self.value)
            soffgrp = Group.objects.get(id=self.value).sensor.all()
            s = Sensor.objects.exclude(id__in=soffgrp)
            self.fields['group'].queryset = group
            self.fields['sensor'].queryset = s
            
class CreateRegulForm(forms.Form):
    """ forms des regulations """
    r = regul()
    name = forms.CharField(max_length=100, label=_("Regulation name"), required=True)
    icon = forms.CharField(max_length=100, label=_("Icon"), required=True)
    type = forms.IntegerField(label=_("Regulation type"), widget=forms.Select(choices=r.form_list_reg()), required=True)  
    
class Regul_assForm(forms.Form):
    """ forms des associations des regulations/capteurs"""
    regul = forms.ModelChoiceField(queryset=Regul.objects.all(),label = _("Regul name"), required=True, empty_label = None)
    sensor = forms.ModelChoiceField(queryset=Sensor.objects.none(), label = _("Sensors"), required=True)  
    
    def __init__(self,*args,**kwargs):
        self.value = kwargs.pop('id_regul', None)
        super(Regul_assForm,self).__init__(*args,**kwargs)
        if self.value:
            regul = Regul.objects.filter(id=self.value)
            soffgrp = Regul.objects.get(id=self.value).sensor.all()
            s = Sensor.objects.exclude(id__in=soffgrp)
            self.fields['regul'].queryset = regul
            self.fields['sensor'].queryset = s
            
class SensorForm(forms.Form):
    """ forms des capteurs"""
    sensor_name = forms.CharField(max_length=100, label = _("Sensor name"), required=True)
    icon = forms.CharField(max_length=100, label=_("Icon"), required=True)
 
class UpdateParameterForm(forms.Form):
    """ forms des parametres"""
    country = forms.CharField(max_length=100, label = _("Country name"), required=True)
    city = forms.CharField(max_length=100, label = _("Weather - City name or zip code"), required=True)
    ssid = forms.CharField(max_length=32, label = _("Wifi name (ssid)"), required=True)
    password = forms.CharField(min_length=8, max_length=63, label = _("Wifi password"), required=True)
    ip = forms.CharField(max_length=19, label = _("Acces point IP"), required=True)
    pricing = forms.CharField(max_length=10, label = _("Tarif Kw/h"), required=True)

class EventForm(forms.ModelForm):
    """ forms des evenements"""
    icon = forms.CharField(max_length=100, label=_("Icon"), required=True)

    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            'end_time': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            }
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super(EventForm, self).__init__(*args, **kwargs)
            # input_formats parses HTML5 datetime-local input to datetime field
            self.fields['start_time'].input_formats = ('%Y-%m-%d',)
            self.fields['end_time'].input_formats = ('%Y-%m-%d',)

class DictListForm(forms.Form):
    """ forms des dict list"""
    def __init__(self,*args,**kwargs):
        self.value = kwargs.pop('type_value_tram', None)
        super(DictListForm,self).__init__(*args,**kwargs)
        self.fields['dict'] = forms.CharField(max_length=100, label = _("Target"), widget=forms.Select(choices=get_list_dict_form(self.value)), required=True)

class RegulForTypeForm(forms.Form):
    """ forms des dicts lists signes"""
    manage_type = manage_type()
    type_value_tram = forms.CharField(max_length=100, label = _("Sensor type"), widget=forms.Select(choices=manage_type.get_list_form()), required=True)
    name = forms.CharField(max_length=100, label=_("Display name"), required=True)
    value = forms.IntegerField(label=_("Value"), required=True)    
    signe = forms.CharField(label=_("Sign"), widget=forms.Select(choices=[('<', _('Lower')), ('<=', _('Equal or lower')), ('==', _('Equal')), ('=!', _('Different ')), ('>=', _('Equal or superior')), ('>', _('Superior'))]), required=True)    
    

Web/Source/SWeb/templates/LifeBox/base.html
{% load i18n %}

{% load static %}
<!DOCTYPE HTML>
<html>
<head>
	<title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/materialdesignicons.min.css' %}" />
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    {% block header %}{% endblock %}
<script>
	function counting(element, msg_element) {
		document.getElementById(element).innerHTML = document.getElementsByClassName(msg_element).length;
	}
	function xhr(method, url) {
		var xhr = new XMLHttpRequest();
		xhr.open(method, url);
		xhr.send();	
	}
	function deleteNotif(event, url)
	{
		console.log(event);
		xhr('GET', url);
		event.remove();
		counting();
	}

</script>
</head>
<body id="body">
<header>
    <div id="header" class="flex center saround">
		<div class="left">
			{% if user.is_authenticated %}
				<a href="/logout"><i class="mdi mdi-logout"></i> {% trans 'Logout' %}</a>
			{% endif %}
		</div>
		<div class="center">
				{% trans 'Home Automation expertise - Made in France' %} <img src="{% static 'images/france_circle.png' %}" id="flag" alt="France Flag"/>
		</div>
		<div class="theme-switch-wrapper right">
			<label class="switch-slider theme-switch-header" for="checkbox">
				<input type="checkbox" id="checkbox" onclick="switchTheme(this)">
				<div class="slider round"></div>
			</label>
			<em>{% trans 'Dark mode'%}</em>
		</div>
    </div>
</header>
<div id="page">
    <div id="headline" class="flex saround">
        <span><a id="logo" href="{% url 'LifeBox:home' %}"></a></span>
        <span>
            <a href="{% url 'LifeBox:calendar' %}">
            <span id="heure">00:00</span>
            <span id="day">{{date.day_date|date:'l d F Y'|title}}</span></a>
        </span>
        
        <span> 
        {% if user.is_authenticated %}
            <a id="meteo" href="{% url 'LifeBox:weather' %}">
                <span>{{weather.city}}</span>
                <img src= {{weather.icon_url}} width="125" align= "middle" >{{weather.temperature}}°C 
            </a>
        {% endif %}
    </span>
    </div>
    {% if user.is_authenticated %}
	<div id="sub_menu" class="flex saround">
	     <a href="{% url 'LifeBox:parameter' %}"><i class="mdi mdi-cog"></i> {% trans 'Parameters' %}</a>
	     <a href="{% url 'LifeBox:sensor' %}"><i class="mdi mdi-leak"></i> {% trans 'Sensor' %}</a>
	     <a href="{{request.META.HTTP_REFERER}}"><i class="mdi mdi-arrow-left"></i>{% trans 'Back' %}</a>
	</div>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>

<div class="notification">
	<span><i class="mdi mdi-bell"></i>	
		{% if count > 0 %} <span id="count-notif" class="count">{{count}}</span> {% endif %}
	</span>

	{% if count > 0 %}
		<span class="message">
			{% for notif in all_notif %}
				<p class="msg" onclick="deleteNotif(this,'{% url 'LifeBox:delete_notif' notif.id %}')" >	
					<a href="?" class="strike">
						{{notif.content}}
					</a>
					{% if notif.ntype == 2 %}
						<a class="fright">
							<i class="mdi mdi-history"></i>
							<span class="bubble">{{notif.delta}} {% trans 'Day' %}</span>
						</a>
					{% endif %}
				</p>
			{% endfor %}
		</span>
	<script>counting("count-notif", "msg");</script>
	{% endif %}
</div> 

<footer>
    <div id="footer">
		{% trans 'Created and Powered by LifeBox Team' %}	
	</div>
</footer>

{% if user.is_authenticated %}
    <div id="popup_menu">
		<figure>
			<img src="{% static 'images/arrow.png' %}">
			<figcaption>{% trans 'HOME' %}</figcaption>
		</figure>
        <div id="apps" class="flex wrap saround">
            {% for group in all_group %}
                <a href="{% url 'LifeBox:group' group.id %}">
					<span> 
						<i class="{{group.icon}}"></i><br>
						<span>{{group.name}}</span>
					</span>
                </a>
            {% endfor %}
            <a href="{% url 'LifeBox:create_group' %}">
				<span>
					<i class="mdi mdi-plus"></i>
					<span>{% trans 'Add group' %}</span>
				</span>
            </a>
        </div>
    </div>
{% endif %}
</body>


<script src="{% static '/JS/theme.js' %}"></script>
<script src="{% static '/JS/time.js' %}"></script>
<script src="{% static '/JS/iconSearch.js' %}"></script>
{% block script %}
{% endblock %}
</html>

Web/Source/SWeb/templates/LifeBox/calendar.html
<!-- templates/calendar.html -->
{% extends "LifeBox/base.html" %}

{% load i18n %}
{%block title %}LS - {% trans 'Calendar' %}{% endblock %}

{% block content %}
    {{ calendar }}
{% endblock %}

Web/Source/SWeb/templates/LifeBox/group_modif.html
<!-- templates/create_group.html -->

{% extends "LifeBox/base.html" %}
{% load i18n %}
{% block title %}LS - {% trans 'Edit group' %}{% endblock %}
{% block content %}

    <div class="information">
        <fieldset>
            <legend>{% trans 'New group' %}</legend>
              <ul>
                <form action="{% url 'LifeBox:modif_group' group.id %}" method="post">
                    {% csrf_token %}
                    <p><label>{{ form.name.label }} :</label>{{ form.name }}</p>  
                    <div id="inputerIcon">
                        <label>Choose icon : </label><input type="text" value="{{form.icon.value}}" id="id_icon" name="icon" onclick="dispo('all', 'block')" onchange="updateIcon(this)" requiered><span><i class="{{form.icon.value}}"></i></span>
                    </div>

                    <div id="all">
                        <div id="ser">Search : <input type="text" id="search" placeholder="Search" onkeyup="searchSelect(this.id, 'icons');"></div>
                        <div id="icons">
                                {% for i in icon %}
                                    <span class="icon"><i class="{{i}}"></i></span>
                                {% endfor %}
                            	</div>
                        </div>
                    <p><input type="submit" value="{% trans 'Create' %}"></p>
                    </div>                    
                </form>
                
              </ul>
        </fieldset>
    </div>
    
<div id="all">
	<div id="ser">Search : <input type="text" id="search" placeholder="Search" onkeyup="searchSelect(this.id, 'ico');"></div>
	<div id="icons">
		<span class="icon"><i class="gg-zoom-out"></i></span>
	</div>
</div>
</html>

{% endblock %}

Web/Source/SWeb/templates/LifeBox/parameter.html
<!-- templates/paremeter.html -->

{% extends "LifeBox/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}LS - {% trans 'Parametres'%}{% endblock %}

{% block content %}

    <div class="information">
        <fieldset>
            <legend>{% trans 'Parameters' %}</legend>
              <ul class="flex saround">
						{% get_current_language as LANGUAGE_CODE %}
						{% get_available_languages as LANGUAGES %}
						{% get_language_info_list for LANGUAGES as languages %}
						{% for language in languages %}
							<li>
								<a href="/{{ language.code }}{{ request.get_full_path|slice:'3:' }}"
								   class="{% if language.code == LANGUAGE_CODE %}selected{% endif %}"
								   lang="{{ language.code }}">
									<img src="{% static 'images/'|add:language.code|add:'.png' %}">  {{ language.name_local|title }}
								</a>
							</li>
						{% endfor %}	
				</ul>
                	<form action="{% url 'LifeBox:parameter' %}" method="post">
						{% csrf_token %}
						<h3 class="hr">Météo</h3>
						<p><label>{{ form.country.label }} :</label>{{ form.country }}</p>  
						<p><label>{{ form.city.label }} :</label>{{ form.city }}</p>  
						<h3 class="hr">Wifi</h3>
						<p><label>{{ form.ssid.label }} :</label>{{ form.ssid }}</p>  
						<p><label>{{ form.password.label }} :</label>{{ form.password }}</p>  
						<p><label>{{ form.ip.label }} :</label>{{ form.ip }}</p>  
						<h3 class="hr">Divers</h3>
						<p><label>{{ form.pricing.label }} :</label>{{ form.pricing }}</p>  
						<p><input type="submit" value="{% trans 'Update' %}"></p>
						</div>                    
					</form>
				 </ul>
			{% if perms.LifeBox.Admin %}
				<div class="information">
					<fieldset>
						<legend>{% trans 'Administration' %}</legend>
						  <ul>
							<li><a href="/admin/"><i class="mdi mdi-account-cog"></i> Administration </a></li>
							<li><a href="{% url 'LifeBox:list_dict' %}">{% trans 'List of dictionnary translation' %}</a></li>
						 </ul>
					</fieldset>
				</div>
				<div class="information">
					<fieldset>
						<legend>{% trans 'Clean database' %}</legend>
							<ul>
								 <form action="{% url 'LifeBox:clean_data' %}" method="post">
									{% csrf_token %}
									<input type="submit" value="{% trans "Clean data" %}">
								</form>
							</ul>
							<ul>
								<form action="{% url 'LifeBox:clean' %}" method="post">
									{% csrf_token %}
									<input type="submit" value="{% trans 'Clean everything' %}">
								</form>
							</ul>
					</fieldset>
				</div>
			{% endif %}
{% endblock %}

Web/Source/SWeb/templates/LifeBox/sensor.html
<!-- templates/create_sensor.html -->

{% extends "LifeBox/base.html" %}
{% load i18n %}

{% block title %}LS - {% trans 'Sensor' %}{% endblock %}

{% block content %}
    <div class="information">
        <fieldset>
            <legend>{% trans 'New sensor' %}</legend>
              <ul>
                <form action="{% url 'LifeBox:sensor'%}" method="post">
                    {% csrf_token %}
                    <p><label> {{ form.sensor_name.label }} :</label> {{ form.sensor_name }}</p>
                    <input type="hidden" name="{{form.icon.name}}" id="{{form.icon.name}}" value="{{form.icon.value}}">
					<input type="submit" value="{% trans 'Create' %}">
                </form>
              </ul>
        </fieldset>
    </div>
        <div class="information">
        <fieldset>
            <legend>{% trans 'Known sensor' %}</legend>
            {% for s in uniq_num_module %}
			<div>
				<div class="legend1">
					<a href="{% url 'LifeBox:delete_sensor' s %}"><i class="mdi mdi-trash-can"></i> {%  trans 'Delete' %} </a>
				</div> 
			   	<h3 class='hr'> {% trans 'Module' %} {{s}}</h3>

				{% for j in all_sensor %}
					{% if s == j.sensor.num_module %}
						   <ul>
							   <li><a href="{% url 'LifeBox:sensor_status' j.sensor.id %}"><i class="{{j.sensor.icon}} space"></i>{% trans 'Sensor' %} {{j.sensor.name}} {% trans 'type' %} {{j.type}}, {% trans 'saved' %} {{j.sensor.date}}</a>
							   <a href="{% url 'LifeBox:sensor_modif' j.sensor.id %}"><i class="mdi mdi-pencil"></i>{% trans 'Edit' %}</a></li>
						   </ul> 
				   {% endif %}
				{% endfor %}
			</div>
			{% empty %}
				<ul>
					{% trans 'No captor saved' %}
				</ul>
			{% endfor %}
        </fieldset>
{% endblock %}